---
name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI + build documentation
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/p/shareyourcloning-linkml
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Build documentation.
        run: |
          poetry install
          mkdir -p docs
          touch docs/.nojekyll
          poetry run make gendoc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          poetry run make mkd-gh-deploy

      - name: Build source and wheel archives
        run: poetry build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
